// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_g0_close
global.__objectDepths[1] = 0; // obj_g0_game_choose
global.__objectDepths[2] = 0; // obj_g0_previous
global.__objectDepths[3] = 0; // obj_g0_next
global.__objectDepths[4] = 0; // obj_engine
global.__objectDepths[5] = -10000; // obj_g_return
global.__objectDepths[6] = 0; // obj_g_title
global.__objectDepths[7] = 0; // obj_g_spin
global.__objectDepths[8] = 0; // obj_g_betless
global.__objectDepths[9] = 0; // obj_g_betmore
global.__objectDepths[10] = 100; // obj_g_bg
global.__objectDepths[11] = 90; // obj_g_frame
global.__objectDepths[12] = 0; // obj_g_money
global.__objectDepths[13] = 0; // obj_g_jackpot
global.__objectDepths[14] = 0; // obj_g_lastwin
global.__objectDepths[15] = 0; // obj_g_betwindow
global.__objectDepths[16] = -99; // obj_showcash
global.__objectDepths[17] = 0; // r1l1
global.__objectDepths[18] = 0; // r2l1
global.__objectDepths[19] = 0; // r3l1
global.__objectDepths[20] = 0; // r4l1
global.__objectDepths[21] = 0; // r5l1
global.__objectDepths[22] = 0; // r1l2
global.__objectDepths[23] = 0; // r2l2
global.__objectDepths[24] = 0; // r3l2
global.__objectDepths[25] = 0; // r4l2
global.__objectDepths[26] = 0; // r5l2
global.__objectDepths[27] = 0; // r1l3
global.__objectDepths[28] = 0; // r2l3
global.__objectDepths[29] = 0; // r3l3
global.__objectDepths[30] = 0; // r4l3
global.__objectDepths[31] = 0; // r5l3
global.__objectDepths[32] = -200; // obj_coin
global.__objectDepths[33] = -2; // obj_counter
global.__objectDepths[34] = -11; // obj_info
global.__objectDepths[35] = 0; // obj_slots
global.__objectDepths[36] = -5; // obj_spin
global.__objectDepths[37] = -5; // obj_betmax
global.__objectDepths[38] = -5; // obj_gold
global.__objectDepths[39] = -5; // obj_lines
global.__objectDepths[40] = -5; // obj_bet
global.__objectDepths[41] = -5; // obj_totalbet
global.__objectDepths[42] = 0; // obj_card
global.__objectDepths[43] = 0; // obj_stack
global.__objectDepths[44] = 0; // obj_draw
global.__objectDepths[45] = 0; // obj_game_over
global.__objectDepths[46] = 0; // obj_transition
global.__objectDepths[47] = 0; // obj_control
global.__objectDepths[48] = 0; // obj_score
global.__objectDepths[49] = 0; // obj_show_bonus_seconds
global.__objectDepths[50] = 0; // obj_star_generator
global.__objectDepths[51] = 0; // obj_star
global.__objectDepths[52] = 0; // card_2c
global.__objectDepths[53] = 0; // card_3c
global.__objectDepths[54] = 0; // card_4c
global.__objectDepths[55] = 0; // card_5c
global.__objectDepths[56] = 0; // card_6c
global.__objectDepths[57] = 0; // card_7c
global.__objectDepths[58] = 0; // card_8c
global.__objectDepths[59] = 0; // card_9c
global.__objectDepths[60] = 0; // card_10c
global.__objectDepths[61] = 0; // card_jc
global.__objectDepths[62] = 0; // card_qc
global.__objectDepths[63] = 0; // card_kc
global.__objectDepths[64] = 0; // card_ac
global.__objectDepths[65] = 0; // card_2d
global.__objectDepths[66] = 0; // card_3d
global.__objectDepths[67] = 0; // card_4d
global.__objectDepths[68] = 0; // card_5d
global.__objectDepths[69] = 0; // card_6d
global.__objectDepths[70] = 0; // card_7d
global.__objectDepths[71] = 0; // card_8d
global.__objectDepths[72] = 0; // card_9d
global.__objectDepths[73] = 0; // card_10d
global.__objectDepths[74] = 0; // card_jd
global.__objectDepths[75] = 0; // card_qd
global.__objectDepths[76] = 0; // card_kd
global.__objectDepths[77] = 0; // card_ad
global.__objectDepths[78] = 0; // card_2h
global.__objectDepths[79] = 0; // card_3h
global.__objectDepths[80] = 0; // card_4h
global.__objectDepths[81] = 0; // card_5h
global.__objectDepths[82] = 0; // card_6h
global.__objectDepths[83] = 0; // card_7h
global.__objectDepths[84] = 0; // card_8h
global.__objectDepths[85] = 0; // card_9h
global.__objectDepths[86] = 0; // card_10h
global.__objectDepths[87] = 0; // card_jh
global.__objectDepths[88] = 0; // card_qh
global.__objectDepths[89] = 0; // card_kh
global.__objectDepths[90] = 0; // card_ah
global.__objectDepths[91] = 0; // card_2s
global.__objectDepths[92] = 0; // card_3s
global.__objectDepths[93] = 0; // card_4s
global.__objectDepths[94] = 0; // card_5s
global.__objectDepths[95] = 0; // card_6s
global.__objectDepths[96] = 0; // card_7s
global.__objectDepths[97] = 0; // card_8s
global.__objectDepths[98] = 0; // card_9s
global.__objectDepths[99] = 0; // card_10s
global.__objectDepths[100] = 0; // card_js
global.__objectDepths[101] = 0; // card_qs
global.__objectDepths[102] = 0; // card_ks
global.__objectDepths[103] = 0; // card_as
global.__objectDepths[104] = 0; // card_joker
global.__objectDepths[105] = 0; // card_back
global.__objectDepths[106] = 0; // blank_card
global.__objectDepths[107] = 0; // natural_royal_hi
global.__objectDepths[108] = 0; // natural_royal_lo
global.__objectDepths[109] = 0; // five_of_a_kind_hi
global.__objectDepths[110] = 0; // five_of_a_kind_lo
global.__objectDepths[111] = 0; // joker_royal_hi
global.__objectDepths[112] = 0; // joker_royal_lo
global.__objectDepths[113] = 0; // straight_flush_hi
global.__objectDepths[114] = 0; // straight_flush_lo
global.__objectDepths[115] = 0; // four_of_a_kind_hi
global.__objectDepths[116] = 0; // four_of_a_kind_lo
global.__objectDepths[117] = 0; // full_house_hi
global.__objectDepths[118] = 0; // full_house_lo
global.__objectDepths[119] = 0; // flush_hi
global.__objectDepths[120] = 0; // flush_lo
global.__objectDepths[121] = 0; // straight_hi
global.__objectDepths[122] = 0; // straight_lo
global.__objectDepths[123] = 0; // three_of_a_kind_hi
global.__objectDepths[124] = 0; // three_of_a_kind_lo
global.__objectDepths[125] = 0; // two_pair_hi
global.__objectDepths[126] = 0; // two_pair_lo
global.__objectDepths[127] = 0; // jacks_or_better_hi
global.__objectDepths[128] = 0; // jacks_or_better_lo
global.__objectDepths[129] = 0; // nothing_hi
global.__objectDepths[130] = 0; // nothing_lo
global.__objectDepths[131] = 0; // hold_button1
global.__objectDepths[132] = 0; // hold_button2
global.__objectDepths[133] = 0; // hold_button3
global.__objectDepths[134] = 0; // hold_button4
global.__objectDepths[135] = 0; // hold_button5
global.__objectDepths[136] = 0; // deal_button
global.__objectDepths[137] = 0; // obj_draw_button
global.__objectDepths[138] = 0; // bet1_button
global.__objectDepths[139] = 0; // bet5_button
global.__objectDepths[140] = 0; // bet10_button
global.__objectDepths[141] = 0; // creds_control
global.__objectDepths[142] = 0; // bet_control
global.__objectDepths[143] = 0; // logo
global.__objectDepths[144] = 0; // play_poker_button
global.__objectDepths[145] = 0; // exit_game_button
global.__objectDepths[146] = 0; // obj_control_new
global.__objectDepths[147] = 0; // betone
global.__objectDepths[148] = 0; // betmax
global.__objectDepths[149] = 0; // deal
global.__objectDepths[150] = 0; // cardbut
global.__objectDepths[151] = -1; // dealer
global.__objectDepths[152] = -2; // cursor
global.__objectDepths[153] = 0; // obj_card_new
global.__objectDepths[154] = -100; // obj_exclaim
global.__objectDepths[155] = 0; // obj_button
global.__objectDepths[156] = -100; // obj_youLose
global.__objectDepths[157] = 0; // obj_control_new_new
global.__objectDepths[158] = 0; // KenoBall
global.__objectDepths[159] = 0; // BtnStart
global.__objectDepths[160] = 0; // BtnBetUp
global.__objectDepths[161] = 0; // BtnBetDown
global.__objectDepths[162] = 0; // BtnClearBoard
global.__objectDepths[163] = 0; // BtnExit
global.__objectDepths[164] = 0; // BtnOptions
global.__objectDepths[165] = 0; // BtnSaveGame
global.__objectDepths[166] = 0; // BtnLoadGame
global.__objectDepths[167] = 0; // BtnNewGame
global.__objectDepths[168] = 0; // KenoSpot
global.__objectDepths[169] = 0; // Timer


global.__objectNames[0] = "obj_g0_close";
global.__objectNames[1] = "obj_g0_game_choose";
global.__objectNames[2] = "obj_g0_previous";
global.__objectNames[3] = "obj_g0_next";
global.__objectNames[4] = "obj_engine";
global.__objectNames[5] = "obj_g_return";
global.__objectNames[6] = "obj_g_title";
global.__objectNames[7] = "obj_g_spin";
global.__objectNames[8] = "obj_g_betless";
global.__objectNames[9] = "obj_g_betmore";
global.__objectNames[10] = "obj_g_bg";
global.__objectNames[11] = "obj_g_frame";
global.__objectNames[12] = "obj_g_money";
global.__objectNames[13] = "obj_g_jackpot";
global.__objectNames[14] = "obj_g_lastwin";
global.__objectNames[15] = "obj_g_betwindow";
global.__objectNames[16] = "obj_showcash";
global.__objectNames[17] = "r1l1";
global.__objectNames[18] = "r2l1";
global.__objectNames[19] = "r3l1";
global.__objectNames[20] = "r4l1";
global.__objectNames[21] = "r5l1";
global.__objectNames[22] = "r1l2";
global.__objectNames[23] = "r2l2";
global.__objectNames[24] = "r3l2";
global.__objectNames[25] = "r4l2";
global.__objectNames[26] = "r5l2";
global.__objectNames[27] = "r1l3";
global.__objectNames[28] = "r2l3";
global.__objectNames[29] = "r3l3";
global.__objectNames[30] = "r4l3";
global.__objectNames[31] = "r5l3";
global.__objectNames[32] = "obj_coin";
global.__objectNames[33] = "obj_counter";
global.__objectNames[34] = "obj_info";
global.__objectNames[35] = "obj_slots";
global.__objectNames[36] = "obj_spin";
global.__objectNames[37] = "obj_betmax";
global.__objectNames[38] = "obj_gold";
global.__objectNames[39] = "obj_lines";
global.__objectNames[40] = "obj_bet";
global.__objectNames[41] = "obj_totalbet";
global.__objectNames[42] = "obj_card";
global.__objectNames[43] = "obj_stack";
global.__objectNames[44] = "obj_draw";
global.__objectNames[45] = "obj_game_over";
global.__objectNames[46] = "obj_transition";
global.__objectNames[47] = "obj_control";
global.__objectNames[48] = "obj_score";
global.__objectNames[49] = "obj_show_bonus_seconds";
global.__objectNames[50] = "obj_star_generator";
global.__objectNames[51] = "obj_star";
global.__objectNames[52] = "card_2c";
global.__objectNames[53] = "card_3c";
global.__objectNames[54] = "card_4c";
global.__objectNames[55] = "card_5c";
global.__objectNames[56] = "card_6c";
global.__objectNames[57] = "card_7c";
global.__objectNames[58] = "card_8c";
global.__objectNames[59] = "card_9c";
global.__objectNames[60] = "card_10c";
global.__objectNames[61] = "card_jc";
global.__objectNames[62] = "card_qc";
global.__objectNames[63] = "card_kc";
global.__objectNames[64] = "card_ac";
global.__objectNames[65] = "card_2d";
global.__objectNames[66] = "card_3d";
global.__objectNames[67] = "card_4d";
global.__objectNames[68] = "card_5d";
global.__objectNames[69] = "card_6d";
global.__objectNames[70] = "card_7d";
global.__objectNames[71] = "card_8d";
global.__objectNames[72] = "card_9d";
global.__objectNames[73] = "card_10d";
global.__objectNames[74] = "card_jd";
global.__objectNames[75] = "card_qd";
global.__objectNames[76] = "card_kd";
global.__objectNames[77] = "card_ad";
global.__objectNames[78] = "card_2h";
global.__objectNames[79] = "card_3h";
global.__objectNames[80] = "card_4h";
global.__objectNames[81] = "card_5h";
global.__objectNames[82] = "card_6h";
global.__objectNames[83] = "card_7h";
global.__objectNames[84] = "card_8h";
global.__objectNames[85] = "card_9h";
global.__objectNames[86] = "card_10h";
global.__objectNames[87] = "card_jh";
global.__objectNames[88] = "card_qh";
global.__objectNames[89] = "card_kh";
global.__objectNames[90] = "card_ah";
global.__objectNames[91] = "card_2s";
global.__objectNames[92] = "card_3s";
global.__objectNames[93] = "card_4s";
global.__objectNames[94] = "card_5s";
global.__objectNames[95] = "card_6s";
global.__objectNames[96] = "card_7s";
global.__objectNames[97] = "card_8s";
global.__objectNames[98] = "card_9s";
global.__objectNames[99] = "card_10s";
global.__objectNames[100] = "card_js";
global.__objectNames[101] = "card_qs";
global.__objectNames[102] = "card_ks";
global.__objectNames[103] = "card_as";
global.__objectNames[104] = "card_joker";
global.__objectNames[105] = "card_back";
global.__objectNames[106] = "blank_card";
global.__objectNames[107] = "natural_royal_hi";
global.__objectNames[108] = "natural_royal_lo";
global.__objectNames[109] = "five_of_a_kind_hi";
global.__objectNames[110] = "five_of_a_kind_lo";
global.__objectNames[111] = "joker_royal_hi";
global.__objectNames[112] = "joker_royal_lo";
global.__objectNames[113] = "straight_flush_hi";
global.__objectNames[114] = "straight_flush_lo";
global.__objectNames[115] = "four_of_a_kind_hi";
global.__objectNames[116] = "four_of_a_kind_lo";
global.__objectNames[117] = "full_house_hi";
global.__objectNames[118] = "full_house_lo";
global.__objectNames[119] = "flush_hi";
global.__objectNames[120] = "flush_lo";
global.__objectNames[121] = "straight_hi";
global.__objectNames[122] = "straight_lo";
global.__objectNames[123] = "three_of_a_kind_hi";
global.__objectNames[124] = "three_of_a_kind_lo";
global.__objectNames[125] = "two_pair_hi";
global.__objectNames[126] = "two_pair_lo";
global.__objectNames[127] = "jacks_or_better_hi";
global.__objectNames[128] = "jacks_or_better_lo";
global.__objectNames[129] = "nothing_hi";
global.__objectNames[130] = "nothing_lo";
global.__objectNames[131] = "hold_button1";
global.__objectNames[132] = "hold_button2";
global.__objectNames[133] = "hold_button3";
global.__objectNames[134] = "hold_button4";
global.__objectNames[135] = "hold_button5";
global.__objectNames[136] = "deal_button";
global.__objectNames[137] = "obj_draw_button";
global.__objectNames[138] = "bet1_button";
global.__objectNames[139] = "bet5_button";
global.__objectNames[140] = "bet10_button";
global.__objectNames[141] = "creds_control";
global.__objectNames[142] = "bet_control";
global.__objectNames[143] = "logo";
global.__objectNames[144] = "play_poker_button";
global.__objectNames[145] = "exit_game_button";
global.__objectNames[146] = "obj_control_new";
global.__objectNames[147] = "betone";
global.__objectNames[148] = "betmax";
global.__objectNames[149] = "deal";
global.__objectNames[150] = "cardbut";
global.__objectNames[151] = "dealer";
global.__objectNames[152] = "cursor";
global.__objectNames[153] = "obj_card_new";
global.__objectNames[154] = "obj_exclaim";
global.__objectNames[155] = "obj_button";
global.__objectNames[156] = "obj_youLose";
global.__objectNames[157] = "obj_control_new_new";
global.__objectNames[158] = "KenoBall";
global.__objectNames[159] = "BtnStart";
global.__objectNames[160] = "BtnBetUp";
global.__objectNames[161] = "BtnBetDown";
global.__objectNames[162] = "BtnClearBoard";
global.__objectNames[163] = "BtnExit";
global.__objectNames[164] = "BtnOptions";
global.__objectNames[165] = "BtnSaveGame";
global.__objectNames[166] = "BtnLoadGame";
global.__objectNames[167] = "BtnNewGame";
global.__objectNames[168] = "KenoSpot";
global.__objectNames[169] = "Timer";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for